### ISSUE TITLE
About error related to firebase

### ISSUE THREAD

**Issue by kelvinkoko** [gmcfall/yjs-firestore-provider#1]
Thanks for sharing the firebase provider. While try to follow the example to use firebase provider. I got some error would like to see whether you encounter this during development. (I am using firebase 9.18, and security rule is set to open for read / write for testing)
At first, i tried to just call `initializeApp()` and pass it to firebaseProvider. I got an error of "Service firestore is not available".
Then i tried to also call ` const firestore = getFirestore(firebaseApp)` before calling firebase Provider. then i got "FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore"
Would like to see whether you may know the possible cause. Thank you.

**Comment by gmcfall** [comment]
I have not encountered this error. It seems like something is wrong with your Firebase configuration.

Can you confirm (via the [Firebase Console](https://console.firebase.google.com/)) that Firestore is enabled within your Firebase project?

Are you able to persist Firestore documents outside the FirestoreProvider?

Try logging the Firestore instance like this:
```javascript
const firestore = getFirestore(firebaseApp);
console.log('firestore', firestore);
```
Does the log show a valid Firestore instance?

Can you supply the full stack-trace of the error you are seeing?

**Comment by kelvinkoko** [comment]
Thanks for the feedback, yes, i tried to use Firestore api to store document directly, it is OK.
The stack-trace
```
index.esm2017.js:147 Uncaught Error: Service firestore is not available
    at Provider.getImmediate (index.esm2017.js:147:1)
    at uh (index.esm.js:14148:1)
    at new FirestoreProvider (index.esm.js:16195:1)
```
uh is the getFirestore in FirestoreProvider constructor
```
...
        this.maxUpdatePause = (config === null || config === void 0 ? void 0 : config.maxUpdatePause) === undefined ? 600 : config.maxUpdatePause;
        this.maxUpdatesPerBlob = (config === null || config === void 0 ? void 0 : config.maxUpdatesPerBlob) === undefined ? 20 : config.maxUpdatesPerBlob;
        this.blobTimeToLive = (config === null || config === void 0 ? void 0 : config.blobTimeToLive) === undefined ? 10000 : config.blobTimeToLive;
        const db = uh(firebaseApp);
        const self = this;
        const extra = Math.floor(2000 * Math.random());
        this.compressIntervalId = setInterval(() => {
...
```

Beside calling `initializeApp`, any other function should be called first? or any collection or setting need to be config?
And which version of firebase you tested with? maybe i can try that too.

**Comment by gmcfall** [comment]
I was able to recreate your error. I am investigating.

**Comment by gmcfall** [comment]
I think the problem has been resolved in version `1.0.0-rc.4`.

Try updating your dependency on `@gmcfall/yjs-firestore-provider` to version `1.0.0-rc.4`.

And let me know if the error is resolved for you.

**Comment by kelvinkoko** [comment]
,Thank you for the update! unfortunately, i still got the same error on getFirestore part in Firebase provider constructor part 🤔

**Comment by gmcfall** [comment]
Thanks for you patience as we continue to troubleshoot your issue. I have uploaded my test harness to the [yjs-firestore-provider-test](https://github.com/gmcfall/yjs-firestore-provider-test) repo in github.

 Can you try running this test harness in your environment?

For your convenience, here's the README:

# yjs-firestore-provider-test

This repository is used to test the [@gmcfall/yjs-firestore-provider](https://www.npmjs.com/package/@gmcfall/yjs-firestore-provider) package

## Installation
```bash
git clone https://github.com/gmcfall/yjs-firestore-provider-test.git
cd yjs-firestore-provider-test
npm install
```


## Running
In the `yjs-firestore-provider-test` folder,

```bash
npm start
```

After the app starts up, check you browser and confirm that no error was thrown.

## Customize the firestore app configuraton
You may also try running the test with your own Firestore configuration.
There are two steps:
1. Replace the `firebaseConfig` value.
2. Replace the `path` value

Open `src/App.tsx` in your favorite editor.

Make the following changes:
```javascript
const firebaseConfig = { /** Put your config here */}
const path = [ /** Put your path here */]
```

**Comment by kelvinkoko** [comment]
Thank you for your investigation and really appreciate your help. i did a quick test to run the test repo, it is working with your config and also the firebase config used in my project. I will further test my project setting to see what went wrong and share the result here

**Comment by kelvinkoko** [comment]
When i create a clean project and test again, it work perfectly!~ actually my previous testing project have some rxdb logic as i am testing different solutions, maybe i mess up something. Anyway, as it doesn't related to this project, let me close this issue. And once again, thank you very much for your help and you great work 👍
